---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jasonjst/public_html
    - cp -r ./games.jasonjstewart.com/scoreboard/build $DEPLOYPATH
    - cp /games.jasonjstewart.com/scoreboard/build/.htaccess $DEPLOYPATH
